version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PAWW2026!
      MYSQL_USER: turtle
      MYSQL_PASSWORD: zaq1@WSX
      MYSQL_DATABASE: turtles_prod
    ports:
      - "3306:3306"
    volumes:
      - ../config:/docker-entrypoint-initdb.d

  php-fpm:
    build:
      context: ../
      dockerfile: docker/Dockerfile.php
    container_name: php-fpm
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: turtle
      DB_PASSWORD: zaq1@WSX
      DB_DATABASE: turtles_prod
    depends_on:
      - mysql
    volumes:
      - ../:/var/www/html

  nginx:
    build:
      context: ../
      dockerfile: docker/Dockerfile.nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - php-fpm
    volumes:
      - ../:/var/www/html